### ISSUE TITLE
RouterLinking with param change

### ISSUE THREAD

**Issue by Donrwalsh** [Donrwalsh/curiouser-paradox#13]
Note what happens when you use navigation buttons to move between "{URL}/3" and just "{URL}". Angular recognizes that the path is slightly different and so it re-initializes the component resulting in duplicate API calls which then causes a brief loading screen rather than the desired smooth transition. See https://angular.io/api/router/BaseRouteReuseStrategy and https://stackoverflow.com/questions/67575397/angular-11-2-9-routerlink-doesnt-re-initialise-same-component

**Comment by lfarvour** [comment]
The preferred routing method is now being used; this was addressed via the linked development branch.
