### ISSUE TITLE
Add Bad Request to all POSTs

### ISSUE THREAD

**Issue by lfarvour** [Donrwalsh/curiouser-paradox#4]
# Success Criteria

- All HTTP POST will return a 400 bad request error if the data is invalid for the endpoint

**Comment by Donrwalsh** [comment]
nestjs class validator is great for this. I applied it to the new comic endpoint in the following commit: https://github.com/Donrwalsh/curiouser-paradox/commit/a490dcad43c2b6306a7a528a400ee86e688dac0e

**Comment by Donrwalsh** [comment]
Went through and added class validation annotations to all existing POSTs, with some additional enhancements based on exploration into NestJS & Swagger functionality.
